package proyecto_energias;

import javax.swing.JButton;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class GraphicsMain extends javax.swing.JFrame {

    public GraphicsMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(jLabel14, "src/proyecto_energias/Images/cables.png");
    }

    private static CalculoCables clcable = new CalculoCables();
    
    private void SetImageLabel(JLabel labelname, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    
    
    private static void enviar() {
        try {

            clcable.setNtuv(Integer.parseInt((String) TuboVertical.getSelectedItem()));
            clcable.setNtuh(Integer.parseInt((String) TuboHorizontal.getSelectedItem()));
            switch (Tsistema.getSelectedIndex()) {
                case 0 -> {
                    clcable.setTiposistema(120);
                }
                case 1 -> {
                    clcable.setTiposistema(380);
                }
            }
            switch (Taislamiento.getSelectedIndex()) {
                case 0 -> {
                    clcable.setTipoaislamiento(1);
                }
                case 1 -> {
                    clcable.setTipoaislamiento(2);
                }
            }
        } catch (NumberFormatException e) {
            clcable.setNtuv(0);
            clcable.setNtuh(0);
            clcable.setTiposistema(0);
            clcable.setTipoaislamiento(0);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Longitudcable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Potencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CTension = new javax.swing.JTextField();
        TemperaturaC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Taislamiento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Tsistema = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TuboHorizontal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TuboVertical = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        calcular_Jboton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA DE CABLES");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ASIGNADOR CABLES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(233, 213, 202));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Longitud cable:");

        Longitudcable.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        Longitudcable.setForeground(new java.awt.Color(255, 255, 255));
        Longitudcable.setCaretColor(new java.awt.Color(204, 204, 204));
        Longitudcable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LongitudcableKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("m");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Potencia requerida");

        Potencia.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        Potencia.setForeground(new java.awt.Color(233, 213, 202));
        Potencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PotenciaKeyTyped(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KW");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Caída Tensión");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Temperatura");

        CTension.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        CTension.setForeground(new java.awt.Color(233, 213, 202));
        CTension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CTensionKeyTyped(evt);
            }
        });

        TemperaturaC.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        TemperaturaC.setForeground(new java.awt.Color(233, 213, 202));
        TemperaturaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperaturaCActionPerformed(evt);
            }
        });
        TemperaturaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TemperaturaCKeyTyped(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("%");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("°C");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TemperaturaC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Longitudcable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CTension, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel9))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Longitudcable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CTension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperaturaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 181, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Taislamiento.setBackground(new java.awt.Color(204, 204, 204));
        Taislamiento.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        Taislamiento.setForeground(new java.awt.Color(233, 213, 202));
        Taislamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PVC", "XLPE o EPR" }));
        Taislamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaislamientoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo aislamiento:");

        Tsistema.setBackground(new java.awt.Color(204, 204, 204));
        Tsistema.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        Tsistema.setForeground(new java.awt.Color(233, 213, 202));
        Tsistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monofásico", "Trifásico" }));
        Tsistema.setSelectedIndex(-1);
        Tsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsistemaActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo sistema:");

        TuboHorizontal.setBackground(new java.awt.Color(204, 204, 204));
        TuboHorizontal.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        TuboHorizontal.setForeground(new java.awt.Color(233, 213, 202));
        TuboHorizontal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        TuboHorizontal.setSelectedIndex(-1);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N Tubo horizontal:");

        TuboVertical.setBackground(new java.awt.Color(204, 204, 204));
        TuboVertical.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        TuboVertical.setForeground(new java.awt.Color(233, 213, 202));
        TuboVertical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        TuboVertical.setSelectedIndex(-1);
        TuboVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuboVerticalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("N Tubo vertical:");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuboHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Tsistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(TuboVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Taislamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuboVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuboHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Tsistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Taislamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        calcular_Jboton.setBackground(new java.awt.Color(204, 204, 204));
        calcular_Jboton.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        calcular_Jboton.setForeground(new java.awt.Color(255, 255, 255));
        calcular_Jboton.setText("Calcular");
        calcular_Jboton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcular_Jboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_JbotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcular_Jboton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(calcular_Jboton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LongitudcableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LongitudcableKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_LongitudcableKeyTyped

    private void PotenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PotenciaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_PotenciaKeyTyped

    private void CTensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTensionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_CTensionKeyTyped

    private void TemperaturaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TemperaturaCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TemperaturaCKeyTyped

    private void calcular_JbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_JbotonActionPerformed
        // TODO add your handling code here:
        enviar();
        float longitudC = 0, deman = 0, ten = 0, temper = 0;
        try {
            longitudC = Float.parseFloat(Longitudcable.getText());
        } catch (NumberFormatException e) {
            longitudC = 0;
        }
        try {
            deman = Float.parseFloat(Potencia.getText());
        } catch (NumberFormatException e) {
            deman = 0;
        }
        try {
            ten = Float.parseFloat(CTension.getText());
        } catch (NumberFormatException e) {
            ten = 0;
        }
        try {
            temper = Float.parseFloat(TemperaturaC.getText());
        } catch (NumberFormatException e) {
            temper = 0;
        }
        if (clcable.getNtuv() > 0) {
            if (clcable.getNtuh() > 0) {
                if (longitudC > 0) {
                    if (clcable.getTiposistema() > 0) {
                        if (deman > 0) {
                            if (clcable.getTipoaislamiento() > 0) {
                                if (ten > 0 && ten <= 100) {
                                    if (temper > 0 && temper <= 80) {
                                        if (clcable.getTipoaislamiento() == 1 && temper > 60) {
                                            JOptionPane.showMessageDialog(null, "A esta temperatura no sirve un aislamiento de PVC");
                                        } else {
                                            clcable.setLongitud(longitudC);
                                            clcable.setDemax(deman);
                                            clcable.setPoct(ten);
                                            clcable.setTemperatura(temper);
                                            if (longitudC > 40) {
                                                clcable.Longitudmayor40();
                                                if (clcable.getS() == 0) {
                                                    JOptionPane.showMessageDialog(rootPane, "EL CABLE NO CUMPLE CON LAS CONDICIONES PROPUESTAS", "INFORMACION", 1);
                                                } else {
                                                    JOptionPane.showMessageDialog(rootPane, "SE NECESITA UN CABLE DE CALIBRE (AWG) " + clcable.getValAwg() + " DE SECCION NOMINAL " + clcable.getS() + " mm^2\n"
                                                            + "ESTE CABLE PERMITE UNA CORRIENTE DE HASTA " + clcable.getCapcom() + " Amperios", "INFORMACION", 1);
                                                }
                                            } else {
                                                clcable.Longitudmenor40();
                                                if (clcable.getS() == 0) {
                                                    JOptionPane.showMessageDialog(rootPane, "EL CABLE NO CUMPLE CON LAS CONDICIONES PROPUESTAS", "INFORMACION", 1);

                                                } else {
                                                    JOptionPane.showMessageDialog(rootPane, "SE NECESITA UN CABLE DE CALIBRE (AWG) " + clcable.getValAwg() + " DE SECCION NOMINAL " + clcable.getS() + " mm^2\n"
                                                            + "ESTE CABLE PERMITE UNA CORRIENTE DE HASTA " + clcable.getCorrp() + " Amperios", "INFORMACION", 1);
                                                }
                                            }
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "La temperatura debe estar en un rango de 10°C y 80°C", "ERROR", 0);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "El porcentaje de caida de tension debe estar entre 1% y 100%", "ERROR", 0);
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un TIPO DE AISLAMIENTO", "ERROR", 0);
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "La demanda maxima debe ser mayor a 0", "ERROR", 0);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un TIPO DE SISTEMA", "ERROR", 0);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "La LONGITUD debe ser Mayor a 0", "ERROR", 0);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un NUMERO DE TUBOS AGRUPADOS HORIZONTALMENTE", "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un NUMERO DE TUBOS AGRUPADOS VERTICALMENTE", "ERROR", 0);
        }

    }//GEN-LAST:event_calcular_JbotonActionPerformed

    private void TsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsistemaActionPerformed

    private void TuboVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuboVerticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuboVerticalActionPerformed

    private void TemperaturaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperaturaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemperaturaCActionPerformed

    private void TaislamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaislamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaislamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicsMain().setVisible(true);
            }
        });
    }

    public Icon setIccono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField CTension;
    private static javax.swing.JTextField Longitudcable;
    private static javax.swing.JTextField Potencia;
    private static javax.swing.JComboBox<String> Taislamiento;
    private static javax.swing.JTextField TemperaturaC;
    private static javax.swing.JComboBox<String> Tsistema;
    private static javax.swing.JComboBox<String> TuboHorizontal;
    private static javax.swing.JComboBox<String> TuboVertical;
    private javax.swing.JButton calcular_Jboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
